"""Publish a :class:`LineageGraph` into OpenMetadata via the official SDK.

The SDK ships as ``openmetadata-ingestion`` and is declared as an extras
dependency (``etl-framework[openmetadata]``). It is imported lazily so that
projects that publish lineage through other means (OpenLineage JSON, custom
ingestion) do not pay the import cost.

The publisher does *not* register source/target tables — it assumes they have
already been ingested into OpenMetadata by the standard ingestion connectors.
We resolve datasets by FQN and fail loudly if any are missing, which avoids
silently creating phantom datasets in the catalog.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any

from .builder import ColumnEdge, DatasetRef, LineageGraph

log = logging.getLogger(__name__)


@dataclass
class OpenMetadataConfig:
    host_port: str  # e.g. "http://openmetadata-server:8585/api"
    jwt_token: str
    # The framework writes Iceberg tables, registered under a database service
    # whose name is configured here. Source FQNs are looked up under each
    # SourceSpec's connection.kind by default.
    iceberg_service: str = "iceberg_warehouse"
    source_service_overrides: dict[str, str] | None = None


class OpenMetadataPublisher:
    """Publish lineage edges to an OpenMetadata instance."""

    def __init__(self, config: OpenMetadataConfig):
        self.config = config
        self._client: Any | None = None

    # ---------------------------------------------------------------- bootstrap

    def _connect(self) -> Any:
        if self._client is not None:
            return self._client
        try:  # pragma: no cover — exercised only with SDK installed
            from metadata.generated.schema.entity.services.connections.metadata.openMetadataConnection import (
                AuthProvider,
                OpenMetadataConnection,
            )
            from metadata.generated.schema.security.client.openMetadataJWTClientConfig import (
                OpenMetadataJWTClientConfig,
            )
            from metadata.ingestion.ometa.ometa_api import OpenMetadata
        except ImportError as exc:
            raise RuntimeError(
                "OpenMetadata SDK not installed; reinstall with "
                "'pip install etl-framework[openmetadata]'"
            ) from exc

        cfg = OpenMetadataConnection(
            hostPort=self.config.host_port,
            authProvider=AuthProvider.openmetadata,
            securityConfig=OpenMetadataJWTClientConfig(jwtToken=self.config.jwt_token),
        )
        self._client = OpenMetadata(cfg)
        return self._client

    # -------------------------------------------------------------------- API

    def publish(self, graph: LineageGraph) -> int:
        """Publish all dataset and column edges. Returns the number of API calls."""
        client = self._connect()
        from metadata.generated.schema.api.lineage.addLineage import AddLineageRequest
        from metadata.generated.schema.type.entityLineage import (
            ColumnLineage,
            EntitiesEdge,
            LineageDetails,
        )
        from metadata.generated.schema.type.entityReference import EntityReference

        # group column edges by (upstream, downstream) so we issue one
        # AddLineageRequest per dataset edge (column edges are nested under it)
        per_edge: dict[tuple[DatasetRef, DatasetRef, str], list[ColumnEdge]] = {}
        for ce in graph.column_edges:
            per_edge.setdefault((ce.upstream, ce.downstream, ce.job), []).append(ce)

        calls = 0
        for de in graph.dataset_edges:
            up_ref = self._resolve(client, de.upstream, EntityReference)
            down_ref = self._resolve(client, de.downstream, EntityReference)
            col_edges = per_edge.get((de.upstream, de.downstream, de.job), [])
            column_lineage = [
                ColumnLineage(
                    fromColumns=[self._column_fqn(de.upstream, ce.upstream_column)],
                    toColumn=self._column_fqn(de.downstream, ce.downstream_column),
                )
                for ce in col_edges
            ]
            details = LineageDetails(
                pipeline=None,
                description=f"generated by etl-framework job {de.job}",
                columnsLineage=column_lineage or None,
            )
            req = AddLineageRequest(
                edge=EntitiesEdge(
                    fromEntity=up_ref, toEntity=down_ref, lineageDetails=details
                )
            )
            client.add_lineage(data=req)
            calls += 1
        log.info("published %d lineage edges to %s", calls, self.config.host_port)
        return calls

    # ----------------------------------------------------------- internals

    def _resolve(self, client: Any, ref: DatasetRef, EntityReference: Any) -> Any:
        from metadata.generated.schema.entity.data.table import Table

        fqn = self._table_fqn(ref)
        table = client.get_by_name(entity=Table, fqn=fqn)
        if table is None:
            raise RuntimeError(
                f"OpenMetadata: table '{fqn}' not found; run ingestion before publishing lineage"
            )
        return EntityReference(id=table.id, type="table")

    def _table_fqn(self, ref: DatasetRef) -> str:
        # Iceberg outputs are under the configured warehouse service.
        if ref.namespace.startswith("iceberg://"):
            db = ref.namespace.removeprefix("iceberg://")
            schema, table = ref.name.split(".", 1)
            return f"{self.config.iceberg_service}.{db}.{schema}.{table}"

        # Source datasets: use service overrides if provided, else <kind>_<host>.
        scheme = ref.namespace.split("://", 1)[0]
        overrides = self.config.source_service_overrides or {}
        service = overrides.get(scheme, scheme)
        # ref.namespace is e.g. "postgres://host:5432/db", we want db at the end
        try:
            db = ref.namespace.rsplit("/", 1)[1]
        except IndexError:
            db = "default"
        schema, table = ref.name.split(".", 1)
        return f"{service}.{db}.{schema}.{table}"

    def _column_fqn(self, ref: DatasetRef, column: str) -> str:
        return f"{self._table_fqn(ref)}.{column}"
